// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyfCIBoGI2Tnhvqk3Q1OnP8VM9xI4bk4U',
    appId: '1:986493928850:android:b0e6287b2b50b97a3c6d4b',
    messagingSenderId: '986493928850',
    projectId: 'aicruit-app',
    storageBucket: 'aicruit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOIIV0UzeY-Ga6Ivt9C0i2G1n4TPFz2ww',
    appId: '1:986493928850:ios:ea9f371a12f896a03c6d4b',
    messagingSenderId: '986493928850',
    projectId: 'aicruit-app',
    storageBucket: 'aicruit-app.firebasestorage.app',
    iosBundleId: 'com.example.resumeAi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuZ062N9e7EeTKMMUt7UmX00gcBTOXY-8',
    appId: '1:986493928850:web:d9c95d40edfc42ed3c6d4b',
    messagingSenderId: '986493928850',
    projectId: 'aicruit-app',
    authDomain: 'aicruit-app.firebaseapp.com',
    storageBucket: 'aicruit-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOIIV0UzeY-Ga6Ivt9C0i2G1n4TPFz2ww',
    appId: '1:986493928850:ios:ea9f371a12f896a03c6d4b',
    messagingSenderId: '986493928850',
    projectId: 'aicruit-app',
    storageBucket: 'aicruit-app.firebasestorage.app',
    iosBundleId: 'com.example.resumeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuZ062N9e7EeTKMMUt7UmX00gcBTOXY-8',
    appId: '1:986493928850:web:b117e0f5c2683e3d3c6d4b',
    messagingSenderId: '986493928850',
    projectId: 'aicruit-app',
    authDomain: 'aicruit-app.firebaseapp.com',
    storageBucket: 'aicruit-app.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDuZ062N9e7EeTKMMUt7UmX00gcBTOXY-8',
    appId: '1:986493928850:web:d9c95d40edfc42ed3c6d4b',
    messagingSenderId: '986493928850',
    projectId: 'aicruit-app',
    authDomain: 'aicruit-app.firebaseapp.com',
    storageBucket: 'aicruit-app.firebasestorage.app',
  );

}